source 'http://rubygems.org'
gem 'oauth2', '~> 0.9', require: 'oauth2'
gem 'multipart-post', '~> 2.0'

group :development do
	gem 'bundler', '~> 1.0'
	gem 'minitest', '~> 5.3'
	gem 'mocha', '~> 1.0'
	gem 'simplecov', '~> 0.8'
	gem 'rubocop', '~> 0.20'
	gem 'rdoc', '~> 4.1'
	gem 'jeweler', '~> 2.0'
	gem 'ansi', '~> 1.4'
	gem 'minitest-reporters', '~> 1.0'
	gem 'vcr', '~> 2.9'
	gem 'webmock', '~> 1.17'
	gem 'guard', '~> 2.6'
	gem 'guard-minitest', '~> 2.2'
	gem 'terminal-notifier-guard', '~> 1.5'
	gem 'guard-rubocop', '~> 1.0'
	gem 'rdoc-generator-fivefish', '~> 0.1'
end
